export enum AccountType {
  BROKERAGE = "BROKERAGE",
  HIGH_YIELD = "HIGH_YIELD",
  BOND_ACCOUNT = "BOND_ACCOUNT",
  RIA_ASSET = "RIA_ASSET",
  TREASURY = "TREASURY",
  TRADITIONAL_IRA = "TRADITIONAL_IRA",
  ROTH_IRA = "ROTH_IRA",
}

