export enum OrderStatus {
  NEW = "NEW",
  PARTIALLY_FILLED = "PARTIALLY_FILLED",
  CANCELLED = "CANCELLED",
  QUEUED_CANCELLED = "QUEUED_CANCELLED",
  FILLED = "FILLED",
  REJECTED = "REJECTED",
  PENDING_REPLACE = "PENDING_REPLACE",
  PENDING_CANCEL = "PENDING_CANCEL",
  EXPIRED = "EXPIRED",
  REPLACED = "REPLACED",
}

